name: GTHub
version: 1.1.2-PREALPHA-SNAPSHOT
main: com.gmail.gogobebe2.gthub.GTHub
description: Basic hub plugin.
author: William Bryant (gogobebe2)
website: gogobebe2@gmail.com
commands:
  permspawn:
permissions:
  gthub.setspawn:
    default: op